### ISSUE TITLE
expression matrix input

### ISSUE THREAD

**Issue by ChengYunazhi** [SchulzLab/JAMI#1]
Hi, should I convert FPKM to log2(FPKM+1), and then fed to JAMI? 

All the best

Yuanzhi

**Comment by SchulzLab** [comment]
Dear Yuanzhi,
the CMI computation uses the ranks of the expression values not the absolute values. Therefore it will not make a difference and you do not need to use log2(FPKM+1).

Hope that helps,
Marcel
